name: "tagged-release"

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: cd build && ./build.sh
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            cd build/output
            *.zip
            *.crx
            *.xpi